up-to-date valgrind is merged into main trunk

diff --git a/valgrind/drd/scripts/run-splash2 b/valgrind/drd/scripts/run-splash2
--- a/valgrind/drd/scripts/run-splash2
+++ b/valgrind/drd/scripts/run-splash2
@@ -10,51 +10,77 @@ function run_test {
   local tmp avg1 stddev1 avg2 stddev2 avg4 stddev4 p
 
   tmp="/tmp/test-timing.$$"
-  rm -f "${tmp}"
 
+  rm -f "${tmp}"
   p=1
   test_output="${1}-p${p}.out" measure_runtime "$@" -p${psep}${p} "${test_args}" | avgstddev > "$tmp"
-  read avg1 stddev1 vsz1 vszdev1 < "$tmp"
+  read avg1 stddev1 vsz1 vszdev1 rest < "$tmp"
   echo "Average time: ${avg1} +/- ${stddev1} seconds." \
        " VSZ: ${vsz1} +/- ${vszdev1} KB"
 
+  if [ "${rest}" != "" ]; then
+    echo "Internal error ($rest)"
+    exit 1
+  fi
+
+  rm -f "${tmp}"
   p=2
   test_output="${1}-p${p}.out" measure_runtime "$@" -p${psep}${p} "${test_args}" | avgstddev > "$tmp"
-  read avg2 stddev2 vsz2 vszdev2 < "$tmp"
+  read avg2 stddev2 vsz2 vszdev2 rest < "$tmp"
   echo "Average time: ${avg2} +/- ${stddev2} seconds." \
        " VSZ: ${vsz2} +/- ${vszdev2} KB"
 
+  if [ "${rest}" != "" ]; then
+    echo "Internal error ($rest)"
+    exit 1
+  fi
+
+  rm -f "${tmp}"
   p=4
   test_output="${1}-p${p}.out" measure_runtime "$@" -p${psep}${p} "${test_args}" | avgstddev > "$tmp"
-  read avg4 stddev4 vsz4 vszdev4 < "$tmp"
+  read avg4 stddev4 vsz4 vszdev4 rest < "$tmp"
   echo "Average time: ${avg4} +/- ${stddev4} seconds." \
        " VSZ: ${vsz4} +/- ${vszdev4} KB"
+  rm -f "$tmp"
+
+  if [ "${rest}" != "" ]; then
+    echo "Internal error ($rest)"
+    exit 1
+  fi
 
   p=1
   test_output="/dev/null" \
-  print_runtime_ratio ${avg1} ${stddev1} ${vsz1} ${vszdev1} $VG --tool=none "$@" -p${psep}${p} "${test_args}"
+  print_runtime_ratio "${avg1}" "${stddev1}" "${vsz1}" "${vszdev1}" "$VG" --tool=none "$@" -p${psep}${p} "${test_args}"
 
   p=4
   test_output="/dev/null" \
-  print_runtime_ratio ${avg4} ${stddev4} ${vsz4} ${vszdev4} $VG --tool=none "$@" -p${psep}${p} "${test_args}"
+  print_runtime_ratio "${avg4}" "${stddev4}" "${vsz4}" "${vszdev4}" "$VG" --tool=none "$@" -p${psep}${p} "${test_args}"
 
   p=4
   test_output="${1}-drd-with-stack-var-4.out" \
-  print_runtime_ratio ${avg4} ${stddev4} ${vsz4} ${vszdev4} \
-    $VG --tool=drd --check-stack-var=yes "$@" -p${psep}${p} "${test_args}"
+  print_runtime_ratio "${avg4}" "${stddev4}" "${vsz4}" "${vszdev4}" \
+    "$VG" --tool=drd --first-race-only=yes --check-stack-var=yes \
+    --drd-stats=yes "$@" -p${psep}${p} "${test_args}"
 
   p=4
   test_output="${1}-drd-without-stack-var-4.out" \
-  print_runtime_ratio ${avg4} ${stddev4} ${vsz4} ${vszdev4} \
-    $VG --tool=drd --check-stack-var=no  "$@" -p${psep}${p} "${test_args}"
+  print_runtime_ratio "${avg4}" "${stddev4}" "${vsz4}" "${vszdev4}" \
+    "$VG" --tool=drd --first-race-only=yes --check-stack-var=no \
+    --drd-stats=yes "$@" -p${psep}${p} "${test_args}"
 
   p=4
-  test_output="${1}-helgrind-4.out" \
-  print_runtime_ratio ${avg4} ${stddev4} ${vsz4} ${vszdev4} $VG --tool=helgrind "$@" -p${psep}${p} "${test_args}"
+  test_output="${1}-helgrind-4-none.out" \
+  print_runtime_ratio "${avg4}" "${stddev4}" "${vsz4}" "${vszdev4}" "$VG" --tool=helgrind --history-level=none "$@" -p${psep}${p} "${test_args}"
+
+  p=4
+  test_output="${1}-helgrind-4-approx.out" \
+  print_runtime_ratio "${avg4}" "${stddev4}" "${vsz4}" "${vszdev4}" "$VG" --tool=helgrind --history-level=approx "$@" -p${psep}${p} "${test_args}"
+
+  p=4
+  test_output="${1}-helgrind-4-full.out" \
+  print_runtime_ratio "${avg4}" "${stddev4}" "${vsz4}" "${vszdev4}" "$VG" --tool=helgrind --history-level=full "$@" -p${psep}${p} "${test_args}"
 
   echo ''
-
-  rm -f "$tmp"
 }
 
 
@@ -99,10 +125,14 @@ fi
 # 13. Virtual memory size ratio for --tool=drd --check-stack-var=yes -p4 versus -p4.
 # 14. Execution time ratio for --tool=drd --check-stack-var=no -p4 versus -p4.
 # 15. Virtual memory size ratio for --tool=drd --check-stack-var=no -p4 versus -p4.
-# 16. Execution time ratio for --tool=helgrind -p4 versus -p4.
-# 17. Virtual memory size ratio for --tool=helgrind -p4 versus -p4.
-# 18. Execution time ratio for Intel Thread Checker -p4 versus -p4.
-# 19. Execution time ratio for Intel Thread Checker -p4 versus -p4.
+# 16. Execution time ratio for --tool=helgrind --history-level=none -p4 versus -p4.
+# 17. Virtual memory size ratio for --tool=helgrind --history-level=none -p4 versus -p4.
+# 18. Execution time ratio for --tool=helgrind --history-level=approx -p4 versus -p4.
+# 19. Virtual memory size ratio for --tool=helgrind --history-level=approx -p4 versus -p4.
+# 20. Execution time ratio for --tool=helgrind --history-level=full -p4 versus -p4.
+# 21. Virtual memory size ratio for --tool=helgrind --history-level=full -p4 versus -p4.
+# 22. Execution time ratio for Intel Thread Checker -p4 versus -p4.
+# 23. Execution time ratio for Intel Thread Checker -p4 versus -p4.
 #
 # Notes:
 # - Both Helgrind and DRD use a granularity of one byte for data race detection.
@@ -113,25 +143,25 @@ fi
 #   granularity does ITC use ? And which m4 macro's have been used by ITC as
 #   implementation of the synchronization primitives ?
 #
-#     1                    2     3      4      5      6     7     8    9   10   11   12  13   14  15   16    17   18    19
-###########################################################################################################################
-# Results:                native       native       native       none      none       DRD       DRD      HG         ITC ITC
-#                         -p1          -p2          -p4           -p1       -p4       -p4      -p4+f     -p4      -p4 -p4+f
-# .........................................................................................................................
-# Cholesky                0.09  11880  0.07  21888  0.65  41883 15.2  5.08  3.9 2.15   17 2.41  13 2.60   50  5.86  239  82
-# FFT                     0.03   6560  0.02  15101  0.02  32176 10.7  8.36 17.0 2.48   92 2.88 113 3.13  156  5.43   90  41
-# LU, contiguous          0.07   3968  0.05  12176  0.06  28584 12.4 13.17 14.8 2.70   89 2.95  80 3.24  135  5.68  428 128
-# Ocean, contiguous       0.19  23208  0.18  31744  0.13  48888  4.8  3.45  7.6 2.17   59 2.58  50 2.75   77  4.01   90  28
-# Radix                   0.20  15008  0.11  23200  0.11  39592 13.1  4.22 23.6 2.23   59 2.67  54 2.87  282  6.23  222  56
-# Raytrace                0.66 206976  0.47 215168  0.47 232235  8.2  1.23 11.5 1.21  262 1.54 101 1.57  291  3.57  172  53
-# Water-n2                0.19  10560  0.09  26944  0.10  59704 11.4  5.65 22.0 1.83 3194 2.92 467 2.99  108  3.49  189  39
-# Water-sp                0.21   4312  0.10  13400  0.10  29496  9.8 12.20 20.7 2.63  254 3.14  64 3.42   99  5.13  183  34
-# .........................................................................................................................
-# geometric mean          0.41  13360  0.09  26319  0.12  48476 10.2  5.37 13.2 2.12  134 2.58  75 2.76  128  4.81  180  51
-# .........................................................................................................................
-# Hardware: dual-core Intel Core2 Duo E6750, 2.66 GHz, 4 MB L2 cache, 2 GB RAM.                                    
-# Software: openSUSE 11.0 (64-bit edition), runlevel 3, gcc 4.3.1, 32 bit executables, valgrind trunk r8795.
-###########################################################################################################################
+#     1                    2     3      4      5      6     7     8    9   10   11   12  13     14  15    16    17  18    19  20    21   22   23
+################################################################################################################################################
+# Results:                native       native       native       none      none       DRD        DRD      HG        HG        HG         ITC ITC
+#                         -p1          -p2          -p4           -p1       -p4       -p4       -p4+f     -p4       -p4       -p4      -p4 -p4+f
+# ..............................................................................................................................................
+# Cholesky                0.11  12016  0.06  22016  0.55  41328 10.3  4.92  1.7 2.14   15 2.61    8 2.61   10  3.96  10  3.96  15  6.14  239  82
+# FFT                     0.02   6692  0.02  14888  0.02  31621 17.0  8.01 20.0 2.48  114 3.15   64 3.28   81  4.52  81  4.52 116  5.56   90  41
+# LU, contiguous          0.08   4100  0.05  12304  0.06  28712 11.1 12.44 18.5 2.64  104 3.18   70 3.18   87  4.84  89  4.84 118  5.55  428 128
+# Ocean, contiguous       0.23  16848  0.19  25384  0.23  42528  6.3  3.78  8.3 2.11   87 2.82   62 4.02   71  3.75  71  3.75 195  5.96   90  28
+# Radix                   0.21  15136  0.14  23336  0.15  39728 12.6  4.10 22.3 2.19   61 2.87   41 2.94   52  4.03  52  4.03  85  6.13  222  56
+# Raytrace                0.63 207104  0.49 215296  0.49 231680  8.9  1.23 12.9 1.20  385 1.38   86 2.10  158  3.70 160  3.70 222  4.15  172  53
+# Water-n2                0.18  10696  0.09  27072  0.11  59832 12.5  5.46 26.7 1.80 3092 3.03  263 3.06   92  3.28  92  3.28  92  3.55  189  39
+# Water-sp                0.20   4444  0.15  13536  0.10  30269 10.6 11.56 27.0 2.52  405 3.29   69 3.42   95  4.59  95  4.59  97  4.73  183  34
+# ..............................................................................................................................................
+# geometric mean          0.14  13024  0.10  25669  0.14  47655 10.8  5.26 13.5 2.08  161 2.71   59 3.03   66  4.05  66  4.05  95  5.13  180  51
+# ..............................................................................................................................................
+# Hardware: dual-core Intel Core2 Duo E6750, 2.66 GHz, 4 MB L2 cache, 2 GB RAM.                                                        
+# Software: openSUSE 11.0 (64-bit edition), runlevel 3, kernel 2.6.30.1, gcc 4.3.1, 32 bit SPLASH-2 executables, valgrind trunk r10648.
+################################################################################################################################################
 
 ####
 # Notes:
diff --git a/valgrind/nightly/bin/nightly b/valgrind/nightly/bin/nightly
--- a/valgrind/nightly/bin/nightly
+++ b/valgrind/nightly/bin/nightly
@@ -6,19 +6,26 @@
 #----------------------------------------------------------------------------
 
 #----------------------------------------------------------------------------
-# Helper function
+# Helper functions
 #----------------------------------------------------------------------------
+
+# Returns the revision number of the source files with date $1.
+get_svn_revision() {
+  svn info -r "{$1}" "${valgrind_svn_repo}" | sed -n 's/^Revision: //p'
+}
 
 runcmd () {
    logfile=$1
    str=$2
    shift 2
 
-   # Header in short logfile
-   echo -n "   $str  ... " >> $logfile.short
+   # Header in short logfile.
+   # We use "printf" to avoid printing a newline;  "echo -n" isn't POSIX and
+   # so isn't supported on all systems.
+   printf "   $str  ... " >> $logfile.short
 
    # Header and command in verbose logfile
-   echo -n "   $str  ... " >> $logfile.verbose
+   printf "   $str  ... " >> $logfile.verbose
    echo "$*" >> $logfile.verbose
 
    # Run the command
@@ -39,26 +46,53 @@ runcmd () {
 #----------------------------------------------------------------------------
 # Startup
 #----------------------------------------------------------------------------
+
+valgrind_svn_repo="svn://svn.valgrind.org/valgrind/trunk"
+
 # Must have exactly two arguments
 if [ $# -ne 2 ] ; then
-    echo "usage: bin/night /path/to/valgrind/nightly <tag>"
+    echo "usage: $0 /path/to/valgrind/nightly <tag>"
     exit 1
 fi
 
 # Get args from command line
-ABT_TOP=$1
-ABT_MACHINE=$2
+DIR=$1
+TAG=$2
 
 # Get times and date
-ABT_START=`date "+%F %H:%M:%S %Z"`
+START=`date "+%F %H:%M:%S %Z"`
 
-svn_old_date=`date --date=yesterday +%Y-%m-%dT%H:%M:%S`
-svn_new_date=`date --date=today     +%Y-%m-%dT%H:%M:%S`
+# This is one of the formats SVN accepts.  Yes, the 'T' appears in the final
+# string, it's supposed to be like that.
+svn_date_format="+%Y-%m-%dT%H:%M:%S"
 
-cd $ABT_TOP
+# The time-and-date from 24 hours ago is tricky;  Linux and Darwin have
+# different ways of getting it, so we try things until something works.
+svn_old_date=
+if [ "z" = "z${svn_old_date}" ] ; then
+    # Linux method.
+    svn_old_date=`date --date=yesterday $svn_date_format 2> /dev/null`
+fi
+if [ "z" = "z${svn_old_date}" ] ; then
+    # Darwin method.
+    svn_old_date=`date -v-24H $svn_date_format 2> /dev/null`
+fi
+if [ "z" = "z${svn_old_date}" ] ; then
+    echo "Sorry, can't work out the time and date for 24 hours ago, aborting"
+    exit 1;
+fi
+
+# The time-and-date for now is easy.
+svn_new_date=`date $svn_date_format`
+
+cd $DIR
+
+# Clean up output files produced by a previous run.
+rm -rf diffs diff.short final new.short new.verbose old.short old.verbose
+rm -rf sendmail.log unchanged.log valgrind-old valgrind-new
 
 # Setup any relevant environment variables from conf/<tag>.conf.
-. conf/$ABT_MACHINE.conf
+. conf/$TAG.conf
 if [ "${ABT_JOBS}" = "" ]; then
   ABT_JOBS=1
 fi
@@ -66,7 +100,7 @@ if [ "${ABT_EVAL}" = "" ]; then
   ABT_EVAL="eval"
 fi
 if [ "${ABT_RUN_REGTEST}" = "" ]; then
-  ABT_RUN_REGTEST="cd valgrind && perl tests/vg_regtest --all"
+  ABT_RUN_REGTEST="make regtest"
 fi
 
 
@@ -74,12 +108,17 @@ fi
 # Check out, build, test
 #----------------------------------------------------------------------------
 
+svn_old_rev="`get_svn_revision ${svn_old_date}`"
+svn_new_rev="`get_svn_revision ${svn_new_date}`"
+if [ "${svn_old_rev}" = "${svn_new_rev}" ]; then
+  echo "Both {$svn_old_date} and {$svn_new_date} correspond to r${svn_new_rev}"\
+       "-- skipping nightly build." >unchanged.log
+  exit 0
+fi
+
 # Do everything twice -- once for the 24 hours old Valgrind, and once 
 # for the current one.
 for logfile in old new ; do
-
-   # Remove the old valgrind/ and vex/ directories
-   rm -rf valgrind vex
 
    # Remove old short and verbose log files, and start the new ones
    for ext in short verbose ; do
@@ -98,19 +137,19 @@ for logfile in old new ; do
    # Check out, build, run tests
    runcmd $logfile \
           "Checking out valgrind source tree" \
-          "svn co svn://svn.valgrind.org/valgrind/trunk -r {$svn_date} valgrind" && \
+          "svn co ${valgrind_svn_repo} -r {$svn_date} valgrind-$logfile" && \
    \
    runcmd $logfile \
           "Configuring valgrind             " \
-          "cd valgrind && ./autogen.sh  && ./configure --prefix=`pwd`/Inst ${ABT_CONFIGURE_OPTIONS}" && \
+          "cd valgrind-$logfile && ./autogen.sh  && ./configure --prefix=`pwd`/valgrind-$logfile/Inst ${ABT_CONFIGURE_OPTIONS}" && \
    \
    runcmd $logfile \
           "Building valgrind                " \
-          "cd valgrind && make -j ${ABT_JOBS} && make -j ${ABT_JOBS} check && make install" && \
+          "cd valgrind-$logfile && make -j ${ABT_JOBS} && make -j ${ABT_JOBS} check && make install" && \
    \
    runcmd $logfile \
           "Running regression tests         " \
-          "${ABT_RUN_REGTEST}"
+          "cd valgrind-$logfile && ${ABT_RUN_REGTEST}"
 
    # Grab some indicative text for the short log file -- if the regtests
    # succeeded, show their results.  If we didn't make it that far, show the
@@ -132,10 +171,14 @@ done
 # Prepare results and send
 #----------------------------------------------------------------------------
 
+# Get times and date
+END=`date "+%F %H:%M:%S %Z"`
+
 # 'final' shows the difference between the old and new results
-echo                                                     >  final
-echo "Nightly build on" $ABT_MACHINE "(" $ABT_DETAILS ")" \
-     "started at" $ABT_START                             >> final
+echo                                               >  final
+echo "Nightly build on" $TAG "(" $ABT_DETAILS ")" >> final
+echo "Started at" $START                          >> final
+echo "Ended   at" $END                            >> final
 
 # If the results differ from 24 hours ago, print extra stuff.
 diff -C1 old.short new.short > diff.short
@@ -143,8 +186,10 @@ changed=$?
 
 if [ $changed != 0 ] ; then
    echo "Results differ from 24 hours ago"      >> final
+   changed_str=""
 else
    echo "Results unchanged from 24 hours ago"   >> final
+   changed_str="(unchanged) "
 fi
 
 # Always show the current results.
@@ -168,7 +213,6 @@ fi
 # Gather up the diffs (at most the first 100 lines for each one) into a
 # single file.
 MAX_LINES=100
-rm -f diffs
 diff_files=`find . -name '*.diff*' | sort`
 if [ z"$diff_files" = z ] ; then
    echo "Congratulations, all tests passed!" >> diffs
@@ -187,7 +231,7 @@ else
 fi
 
 # Use the conf/<tag>.sendmail script to email the results.
-conf/$ABT_MACHINE.sendmail \
-   "$ABT_START nightly build ($ABT_MACHINE, $ABT_DETAILS)" \
+conf/$TAG.sendmail \
+   "$changed_str$START nightly build ($TAG, $ABT_DETAILS)" \
    final \
-   diffs
+   diffs > sendmail.log 2>&1
